### PR TITLE
adding prioritization fees for keeper instructions

### PR DESCRIPTION
**Pull request by godmodegalactus**

### CODE REVIEW

**Comment by KirillLykov** [comment]
let me check this out

**Comment by KirillLykov** [comment]
the data from runs is noisy, so the variance of one simulation is higher that the effect of the fees priorities. Maybe in long run it will be more evident. For example:

Before:
```
mango-bencher at 490 secs
Recently sent transactions could not yet be confirmed and would be confirmed shortly.

Number of expected marker making transactions : 36000
Number of transactions sent : 42105 (including keeper)
Market Maker transactions : Sent 36000, Successful 26005
Keeper Cosume Events : Sent 4287, Successful 2906
Keeper Cache Price : Sent 202, Successful 184
Keeper Update and Cache Quote Bank : Sent 202, Successful 182
Keeper Update Root Banks : Sent 202, Successful 183
Keeper Cache Root Banks : Sent 202, Successful 179
Keeper Update Perp Cache : Sent 202, Successful 181
Keeper Update Funding : Sent 808, Successful 737
Transactions confirmed 95%
Transactions successful 72%
Transactions timed out 0%
```

After:
```
mango-bencher at 492 secs
Number of expected marker making transactions : 36000
Number of transactions sent : 41521 (including keeper)
Market Maker transactions : Sent 36000, Successful 20171
Keeper Cosume Events : Sent 3691, Successful 2558
Keeper Cache Price : Sent 183, Successful 166
Keeper Update and Cache Quote Bank : Sent 183, Successful 162
Keeper Update Root Banks : Sent 183, Successful 161
Keeper Cache Root Banks : Sent 183, Successful 159
Keeper Update Perp Cache : Sent 183, Successful 161
Keeper Update Funding : Sent 915, Successful 815
Transactions confirmed 96%
Transactions successful 58%
Transactions timed out 0%
```

**Comment by KirillLykov** [comment]
Looks like there are still few successful txs
Screenshot 2023-04-08 at 21 32 18

**Comment by godmodegalactus** [comment]
Interesting results

**Comment by godmodegalactus** [comment]
Added errors in stats to get more info on why transactions are failing.

**Review by mschneider — APPROVED** [review]

**Pull request merged**
